### ISSUE TITLE
Switch to travis

### ISSUE THREAD

**Issue by svenwltr** [rebuy-de/consul-java-client#3]

**Comment by florian-zeidler** [comment]
**TODO**
- [ ] Create a user at  GitHub for use with TravisCI, which is only allowed to see public repositories
- [ ] Decide and if wanted remove consul-java-client from jenkins by deleting .jenkins.yml
- [ ] Create a Travis CI Maven Build see: https://docs.travis-ci.com/user/languages/java
- [ ] Be happy
